#Utilizamos la imagen de python con alpine para reducir espacios
FROM python:3.12.8-alpine3.20

#creamos el workdir
WORKDIR /app

# Instalamos dependencias del sistema necesarias para mysqlclient
RUN echo "Instalando las dependencias de la maquina" && apk add --no-cache \
    mariadb-connector-c-dev \
    gcc \
    musl-dev \
    openssl 

#copiamos la app al workdir del contenedor
COPY ./ .

#instalamos las dependencias
RUN echo "Instalando las deps de python " && pip install django djangorestframework mysqlclient gunicorn django-environ django-cors-headers

EXPOSE 8000

RUN echo "Estamos generando el certificado para el backend" && sh backend-ssl.sh   

CMD [ "gunicorn", "core.wsgi:application","--bind", "0.0.0.0:8000", "--workers", "3" ]
